project:
  type: website

resources:
  - data/centers_with_google_maps_and_website_information.json

website:
  title: "Buscador de establecimientos"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Encuentra tu establecimiento
        href: map.qmd
      - text: Contacto
        href: contacto.qmd
  search: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
