project:
  type: website
  output-dir: docs


execute:
  freeze: auto    # only re-render files whose inputs changed
  cache: true     # speed up code chunks that do run

resources:
  - data/centers_with_google_maps_and_website_information.json

website:
  title: "Buscador de establecimientos"
  site-url: "https://fariasmartin.github.io/tw"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Encuentra tu establecimiento
        href: map.qmd
      - text: Contacto
        href: contacto.qmd
  search: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
