name: Build Quarto to docs

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'          # avoid infinite loops when the workflow pushes docs
      - '.github/**'       # optional
      - 'README.md'        # optional
  workflow_dispatch:       # allow manual runs

permissions:
  contents: write          # allow pushing to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: stable

      - name: Render site
        run: quarto render

      - name: Prepare docs folder
        run: |
          rm -rf docs
          mkdir docs
          cp -r _site/* docs/

      - name: Commit updated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update docs [skip ci]" || echo "No changes"
          git push
